.PHONY: test test-unit test-coverage release

release:
	$(MAKE) -C sqirvy_cli release
test:
	$(MAKE) -C sqirvy_cli test

test-unit:
	$(MAKE) -C sqirvy_cli test-unit

test-coverage:
	$(MAKE) -C sqirvy_cli test-coverage