.PHONY: test

test:
	python -m unittest sqirvy_cli.test_cli
	# python -m sqirvy.anthropic_test
	# python -m sqirvy.gemini_test
	# python -m sqirvy.openai_test
	# python -m sqirvy.llama_test

build:
	python -m build
