[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sqirvy_cli"
version = "2025.0.0"
authors = [
    { name="david howard" },
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
]

[project.scripts]
sqirvy_cli = "sqirvy_cli.main:main"
